apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  labels:
    app: backend
data:
  QUARKUS_DATASOURCE_DB_KIND: postgresql
  QUARKUS_DATASOURCE_USERNAME: weather
  QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://postgres:5432/weather_db
  QUARKUS_HTTP_PORT: "8090"
  QUARKUS_HTTP_HOST: "0.0.0.0"
  QUARKUS_HTTP_CORS: "true"
  QUARKUS_HTTP_CORS_ORIGINS: "*"
  QUARKUS_HTTP_CORS_METHODS: "GET,POST,PUT,DELETE,OPTIONS"
  AIRPORT_CSV_PATH: "/app/data/airports.csv"
  AIRPORT_CSV_LOAD_ON_STARTUP: "true"
  AIRPORT_CSV_SKIP_IF_EXISTS: "true"
