apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - postgres
  - backend
  - frontend

commonLabels:
  app.kubernetes.io/part-of: weather-dashboard
  app.kubernetes.io/managed-by: argocd

namespace: weather-dashboard
