apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: weather-dashboard-dev

bases:
  - ../../base

namePrefix: dev-

commonLabels:
  environment: dev

patchesStrategicMerge:
  - backend-patch.yaml
  - frontend-patch.yaml

images:
  - name: quay.io/vincent-tsugranes/weather-backend
    newTag: "latest"
  - name: quay.io/vincent-tsugranes/weather-frontend
    newTag: "latest"
